### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Query42** [utility-ship-captain/The-Hexxed-Game-of-Life#2]
Research open source licenses. Write up a brief summary of each choice you think is worth considering and put it in comments here.

**Comment by Query42** [comment]
Right now I'm leaning toward the [MIT License](http://choosealicense.com/licenses/mit/). It is pretty simple, basically just allows people to use the project however they want. Specificies that we're not to be held liable for the use of the project, and tells people that if they use a significant portion of the project they have to include the same license. I don't plan to use this work commercially and see no reason we shouldn't allow others free access to it, personally.

**Comment by HickoryJoe** [comment]
Took a look at that license, it seems perfect for this project. I figured this is mostly for fun and sharing!

**Comment by Query42** [comment]
Captus mentioned on Slack that he thought it was appropriate as well, so unless I hear otherwise I'm gonna plan on implementing the MIT license (or you could, Joe)

**Comment by HickoryJoe** [comment]
I'm on it, Cap'n! =)

**Comment by HickoryJoe** [comment]
License file is finished and uploaded, going to close this out for now!
