### ISSUE TITLE
Rules for GoL

### ISSUE THREAD

**Issue by Query42** [utility-ship-captain/The-Hexxed-Game-of-Life#3]
Research rules for 'The Game of Life' and put them in a file named RULES.txt in the root of the project.

**Comment by Query42** [comment]
Rules document in place. Closing issue.

**Comment by utility-ship-captain** [comment]
The rules look pretty straight forward, but there's one detail I'm a little unclear on:

> Each "cell" in the grid exists in a "populated" or "unpopulated" state.
> The program will "iterate," changing the state of the grid.
> In each iteration, each cell will simultaneously check the state of itself and its eight neighbors.
> 
> If the cell is unpopulated and exactly three neighbors are populated, it will become populated.
> If the cell is populated and has two or three populated neighbors, it will remain populated.

Is there an order in which the cells are updated?
It seems that by updating a cell, it could change the behavior of one of its neighbors.  Or are all changes on the board evaluated before any updates are made, then all updates are applied (before the next cycle)?

**Comment by Query42** [comment]
Each cell on the board is evaluated according to the state of the board before any changes are made. Then the board state changes all at once, and the process begins again.

**Comment by Query42** [comment]
Each cycle of the game would ideally appear instantaneous to the viewer, the whole board updated at once as each cell reacts to the previous game state. It shouldn't matter what order we check the cells in, in other words.
