### ISSUE TITLE
Modified rules

### ISSUE THREAD

**Issue by Query42** [utility-ship-captain/The-Hexxed-Game-of-Life#4]
Rewrite the rules for 'The Game of Life' to fit the hex grid idea, and put them in a file named RULES6.txt in the root of the project.

**Comment by Query42** [comment]
This might be a little trickier than it first appears. It will be difficult to predict what specific rules we should use without either running a pencil-paper simulation or tweaking the rules once we have some code in place. Should we aim for a "guess" to code in first and tweak as necessary, or try to get some knowledge before we start coding?

**Comment by utility-ship-captain** [comment]
My understanding of the basic rules is that they're all based on 'number of neighbors'.  I would expect that we can translate rules into mathematical rules with variables.
If that's not possible, then yes, a best guess is a great place to start, and we can modify the rules later.

**Comment by Query42** [comment]
Yeah, that's true. They are all based on number of neighbors (also whether or not the cell is live to begin with).

My question was more specific: how many neighbors should be grounds for a cell becoming populated and/or surviving?

Along those lines, from Wikipedia:
Conway chose his rules carefully, after considerable experimentation, to meet these criteria:

There should be no explosive growth.
There should exist small initial patterns with chaotic, unpredictable outcomes.
There should be potential for [von Neumann universal constructors](https://en.wikipedia.org/wiki/Von_Neumann_universal_constructor).
The rules should be as simple as possible, whilst adhering to the above constraints.

**Comment by Query42** [comment]
Another thought: on a cartesian grid, each cell has 8 neighbors. On a hex grid, each cell has 6 neighbors. So, we're probably going to want to slightly lower Conway's numbers. Conway had 3 neighbors for birth, 2/3 for survival. Maybe for a first target, lower birth to 2 and leave survival at 2/3?

**Comment by HickoryJoe** [comment]
Those rules look good to me, and so do the numbers. =)

**Comment by Query42** [comment]
RULES6 file is created with the discussed parameters!
