### ISSUE TITLE
Repository file structure

### ISSUE THREAD

**Issue by Query42** [utility-ship-captain/The-Hexxed-Game-of-Life#5]
Research recommended file/directory structure for Python projects, and implement it in the project using empty directories and files using your best judgement for file names reflecting their contents. This may just be one file. Outline the layout in a file named LAYOUT1.txt in the root of the project. The project layout will almost certainly change.

**Comment by utility-ship-captain** [comment]
I've found this to be a pretty good resource in the past: http://docs.python-guide.org/en/latest/writing/structure/

This is going to be a relatively small project, so some of these details may not apply, but sticking to the general layout is good practice and makes scaling up projects a lot easier.

**Comment by Query42** [comment]
Layout created and repo structure modified to fit layout; closing issue.
